version: '3.9'

services:

  mysql-development:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CurrencyExchangeDB
      MYSQL_USER: aku
      MYSQL_PASSWORD: aku
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - currency-network

  naming-server:
    image: akarshippili/namingserver:1.0-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-exchange:
    image: akarshippili/currencyexchangeservice:1.0-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-development:3306/CurrencyExchangeDB
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    depends_on:
      mysql-development:
          condition: service_healthy
      naming-server:
          condition: service_started
      
  
networks:
  currency-network: